### ISSUE TITLE
Missing dotnet-core template

### ISSUE THREAD

**Issue by ertay** [alexa/ask-toolkit-for-vscode#13]
I am trying to create a .NET Core based skill using the toolkit in VS Code, but the only options that show up for me are NodeJS and Python3. I followed the getting started guide to set up the toolkit and I have installed all the prerequisites. I also have VS 2019 Community installed on the side with multiple versions of .NET Core installed (2.0 and above.

Anyone have any ideas why I am not seeing the .NET template?

** Environment Details **

- OS: Windows
- VS Code version: 1.41.1
- ASK Extension Version: 1.02

**VS Code version**:

**Comment by nikhilym** [comment]
Hey @ertay , thanks for the issue. At the moment, we only provide support for building `NodeJS` and `Python` skills through our ASK NodeJS and Python SDK. We do not have a .NET SDK at the moment, and hence have no .NET templates for the skill. Hope this clarifies your question. 

Please feel free to close this issue if you do not have any other problems. Thanks.

**Comment by ertay** [comment]
Thanks for the quick reply! Apparently I was looking at a video of the AWS Toolkit, and that one does have .NET support :)

Are there any plans to add .NET support to the Alexa toolkit?

**Comment by nikhilym** [comment]
Unfortunately, we cannot comment on new features/products. However, you can check/raise a feature request for this in our [user voice](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote?category_id=322783) so that the appropriate teams will look into it and respond on that.

I am closing this issue for now. Please feel free to create a new issue if you are having problems with the plugin or have any feature requests for us. Thanks.
