### ISSUE TITLE
Support for ASK CLI v2.0.x

### ISSUE THREAD

**Issue by habuma** [alexa/ask-toolkit-for-vscode#15]
**Description:**

As of last week, ASK CLI v2.0.0 was released (and v2.0.1 shortly thereafter). Currently, the VSCode extension only works with ASK CLI v1.x, making it difficult to take advantage of for v2.0.x-created projects.

**Steps to reproduce the issue:**
1. Update to the latest ASK CLI
2. Attempt to edit the interaction model, fulfillment code, or skill manifest to take advantage of intellisense and schema validation. It doesn't work because the files are now in new paths.
3. Attempt to use the VSCode extension to create a new project (and possibly other `ask` commands). They won't work because the CLI has changed.

**Observed result:**

Intellisense, snippets, and JSON schema features won't work in the new project structure created from ASK CLI v2. This is because the configuration is geared toward specific paths and those paths have changed. 

Some of the ASK commands in the command palette won't work as expected because the ASK CLI has changed.

**Expected result:**

The extension would provide all of the same benefits for ASK CLI v2 as it did for ASK CLI v1.x. (Or, there would be a separate extension that offers those same benefits for ASK CLI v2.)

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Not that it should matter much, but this was on Mac.

**VS Code version**: 
1.44.0

**Comment by ziolelle** [comment]
I confirm using ask-cli v2.0.x that a simple Command Palette "ASK: Create a skill from a template" create an error "command ask init -l" doesn't support "-l" parameter.
 It works with ask-cli v1.7.23

**Comment by nikhilym** [comment]
Hey @habuma , @ziolelle . Thanks for raising this up & sorry for the inconvenience. As you may have already checked, `ASK CLI v2` has refactored a lot of commands. As you may have already observed, since the plugin wraps around the CLI commands to perform some actions, upgrading CLI to the latest version breaks the plugin. 

We are working with the CLI team to figure out the best way forward, without breaking our tool users experience. For now, we request you to install the `CLI v1` to get through the plugin operations.

**Comment by nikhilym** [comment]
Hey @habuma , @ziolelle , we have released a [new version of the extension](https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2020/07/ask-sdk--slot-management--testing--and-analytics-), that is completely decoupled from ASK CLI. Please update your local extension version and try it out. 

If you think we still need to have ASK CLI functionality in the extension, please open a [feature request](https://github.com/alexa/ask-toolkit-for-vscode/issues/new?labels=feature-request&template=feature_request.md) so that we can collect more feedback regarding the same. 

Thanks once again. Closing this issue at the moment.
