### ISSUE TITLE
Setting up vscode ASK toolkit v2 totally wiped my entire .code-workspace file (Remote Explorer)

### ISSUE THREAD

**Issue by talkingnews** [alexa/ask-toolkit-for-vscode#21]
**Describe the bug**

Setting up vscode toolkit v2 totally destroys entire existing .code-workspace file

**To Reproduce**

Open existing Amazon-hosted existing skill in dev console, select "open in vs code" option.
VSCode opens, popup dialog asks "choose folder". Home directory is default.
As soon as I selected it, the vscode remote workspace window closed and then re-opened with the original contents of my .code-workspace replaced with just the new skill folder. I can rebuild, but not cool!

**Expected behavior**

Not over-write my existing.code-workspace file (please!)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Node v 12.18.2
-   Visual Studio Code Version: 1.47.2
-   Alexa Skill Toolkit Version: 2.0.0

**Additional context**

User Remote Explorer for development, so also can't seem to figure out how to login. Will file as seperate question

**Comment by nikhilym** [comment]
Hey @talkingnews , thanks for reporting this behavior and sorry for the trouble. Due to some extension activation issues as well as performance w.r.t having multiple skills in a workspace, our initial solution of opening up a skill folder was to dispose other webviews/text editors, and open the skill as a clean state. [ref](https://github.com/alexa/ask-toolkit-for-vscode/blob/fdcf6dfd536a473396ffd11365c5b9c5d157f46c/src/utils/workspaceHelper.ts#L54)

But looks like our logic for updating the workspace folders is not entirely correct. We will look into fixing this soon. Once again, thanks for reporting this and for using our extension.

**Comment by nikhilym** [comment]
Hey @talkingnews , sorry for responding late. We fixed this issue in the latest version of the toolkit `2.1.0`, along with more options when trying to add more than 1 skill in the current workspace. Hope the fix works for you. Please update the extension to the latest version, try it out and let us know if you still face issues. Thanks.
