### ISSUE TITLE
How do I login without a browser?

### ISSUE THREAD

**Issue by talkingnews** [alexa/ask-toolkit-for-vscode#22]
**Desktop (please complete the following information):**

-   OS running local VScode Windows NT x64 10.0.1.19041
-   OS running Remote Explorer for VSCode: (hence, extension, git etc): Ubuntu 20.04 (Linux x64 5.4.0-1018-aws)
-   VS Code version: 1.47.2
-   Alexa Skill Toolkit extension version: 2.0.0

**Question**

I see that it has been made difficult to use the debugging part of the the Toolkit for the majority (eg non-US users), and I need to jump through a number of steps https://github.com/alexa/ask-toolkit-for-vscode/wiki/Setting-Up-Local-Debugging-In-Other-Regions

However, even when that it done, how do I activate and enable the login? With ask-cli, there is a --no-browser option.
But I cannot find the equiveland for the toolkit, or any docs for this - it is possible that I will discover a config file somewhere after posting this question, however, I think it should be documented.

**Comment by nikhilym** [comment]
Hey @talkingnews , good point. Currently, we do not have a `--no-browser` kind of functionality in the extension itself, since there are some external links that we need for setting up the extension and also for other skill action functionalities. 

We basically share the credentials logic with `ask-cli` and hence if you are creating/updating profiles using [`ask-cli v2.13.0`](https://github.com/alexa/ask-cli/blob/develop/CHANGELOG.md#2130-2020-07-21), you should be able to use the same profile for trying local debugging as well. Btw the config file is at `$HOME/.ask/cli_config`. But we strongly recommend you to **not update the file manually** which can lead to breaking the credential management of our tools. Please let us know if this helps.

**Comment by nikhilym** [comment]
As for the `--no-browser` option in the extension itself, we need to look into the details on how that can affect the UX of the workflows in the extension. I will leave that as a feature request on the extension and depending on the community feedback, figure out how we can prioritize on allowing that. Thanks.

**Comment by wyajunjun** [comment]
Hey @talkingnews , Could I know which remote development you are using when encountered this issue? SSH, containers or WSL?

**Comment by talkingnews** [comment]
Hi there; it's via ssh.

Yes, I can open the prompt "Do you want code to open the external website".

But then of course, that open the browser on my local machine. I can login, but then when complete it says "the page at 127.0.0.1 cannot be found".

Would you like me to make a quick screencast video?

**Comment by wyajunjun** [comment]
Thanks for the info! @talkingnews I encountered the same issue, will look into that.

**Comment by wyajunjun** [comment]
Hey @talkingnews This issue caused because the port is unvisited by default over SSH remote development, can you refer to https://code.visualstudio.com/docs/remote/ssh#_forwarding-a-port-creating-ssh-tunnel to forward the port 9090? The setup on VSCode SSH extension will be like this, let me know whether this works :)
![961595989153_ pic_hd](https://user-images.githubusercontent.com/68405785/88841485-e83d8e00-d192-11ea-8a82-dc1723c9c13d.jpg)

**Comment by talkingnews** [comment]
Hi @wyajunjun - wow! Of course - what a good idea! Why didn't I think of that?!?
It works perfectly now - thank you! I think maybe that info could be added to the basic "click here to login screen".
THANK YOU THANK YOU THANK YOU!

**Comment by nikhilym** [comment]
Closing this, since the issue has been addressed and we don't need a new `--no-browser` option at the moment to work through the extension.
