### ISSUE TITLE
refresh_token' of undefined and then Missing Options

### ISSUE THREAD

**Issue by macasas** [alexa/ask-toolkit-for-vscode#23]
Open VS Code
Click ASK button
Click Manage Account Profiles
Add name to Create New Profile
Click Create
Browser opens in developer.amazon.com, showing App Request.
Click Allow
Browser says Sign in successful. You may now close this page and return to VSCode.
Return to VSCode

Profile Manager tab says All done!
The profile has been linked to your Amazon Developer account and made active in the toolkit. 
It can be changed at any time through the status bar selector, and additional profiles may be created through the Profile Manager.

Popup notification, bottom right hand corner says
Alexa-Hosted skills retrieval failed. Reason: Cannot read property 'refresh_token' of undefined

Status Bar shows added account, click, and select.  The accounts are listed, and after a few attempts to connect the account some have a Vendor ID and others say undefined.

Select the required account with valid Vendor ID
Select Import Skill
It loads the skill

At which point none of the options are available to manage the skill, except Documentation.
<img width="604" alt="Screenshot 2020-07-25 at 21 15 34" src="https://user-images.githubusercontent.com/910082/88465573-1df52500-cebc-11ea-99e2-32d3e2f9d6c1.png">

According to https://raw.githubusercontent.com/alexa/ask-toolkit-for-vscode/master/media/docs/deploy_skill.gif
There should be a whole bunch of options.
<img width="406" alt="Screenshot 2020-07-25 at 21 22 00" src="https://user-images.githubusercontent.com/910082/88465733-ffdbf480-cebc-11ea-99aa-e5b166b9a2ce.png">

**Comment by nikhilym** [comment]
Hey @macasas , thanks for reporting this issue. Can you please provide us with the following information, so that we can investigate this better : 

- What does the status bar show for your `ASK Profile: `?
- Clicking on that status bar icon, you should get a quick pick for profiles. Does your intended profile contains a `vendor id`?
- Were you trying to import a skill when you got this popup, or just when you signed into the profile? 
> Popup notification, bottom right hand corner says `Alexa-Hosted skills retrieval failed. Reason: Cannot read property 'refresh_token' of undefined`
- Can you try to delete and re-create the profile (through `Profile Manager` under the hamburger menu (`...`) of `Skills Management` pane) and see if this issue still persists? If it does persist, do you mind providing the extension logs? For the extension logs, you can change the `log level` setting to `debug`/`verbose` in extension settings, open the `ASK Toolkit` Output window and try this step.
- Can you also provide your workstation information by running `Alexa: About Alexa Skills Toolkit` command in the Command Palette?
- This is probably unrelated, but just to understand your system state, do you have [`ask-cli`](https://www.npmjs.com/package/ask-cli) installed and if so, which version of it? Are you able to do skill operations through `ask-cli`?

**Comment by macasas** [comment]
The status bar shows 5 accounts, these are the numerous times I tried to connect to my Alexa account.
I have 2 Alexa accounts.
Default and botchat are the same account, the first connect  worked (default has VendorID),
But I am unable to test any skill in this account for some reason
So I tried to connect to d@vidmac.com, and it failed
I tried vidmac and it failed
I tried vid and it failed
I tried botched.xyz and it failed
Then I found the status bar and could see this list
d@vidmac.com, vidmac and vid are all attempts to connect to my second account, all attempts said they failed, yet as you can see two actually worked and have vendor IDs.

What I actually wanted to do was replace my default account with another account connection
I can delete all accounts except the default, hence having to add them.

The popup only comes when trying to connect to an account.
It then listed all my skills and allowed me to import a skill
But then all the menu items disappeared so I couldn’t send it back
2nd image below, looking at imported skill, but what can I do with it, where are the commands?

OS: Darwin x64 19.3.0
Visual Studio Code Version: 1.47.2
Alexa Skills Toolkit Version: 2.0.0
Git Version: git version 2.21.1 (Apple Git-122.3)

ASK-CLI was installed I think as part of trying to run a Jovo (not Java) project, and it did upload a skill into my dev account, but I have not used it for a while, so I’m not sure of any commands right now.

**Comment by nikhilym** [comment]
Thanks for providing the information @macasas .

> Default and botchat are the same account, the first connect  worked (default has VendorID),
> But I am unable to test any skill in this account for some reason

By testing, do you mean downloading a hosted skill or trying local-debugging feature on a skill?

> What I actually wanted to do was replace my default account with another account connection
> I can delete all accounts except the default, hence having to add them.

Can you try deleting all profiles, restart vscode and recreate the `default` profile please?

> The popup only comes when trying to connect to an account.
> It then listed all my skills and allowed me to import a skill
> But then all the menu items disappeared so I couldn’t send it back

This is interesting. From the [code](https://github.com/alexa/ask-toolkit-for-vscode/blob/fdcf6dfd536a473396ffd11365c5b9c5d157f46c/src/runtime/lib/utils/profileHelper.ts#L56), I checked that the menu items shouldn't disappear unless the signed in profile is not authorized. I am wondering how could that be the case here since you tried signing in multiple times already, and couple of those times, you also got the vendor id. Maybe try deleting all profiles and recreating one and let us know what happens. Also, it would be great if you can provide the extension logs as mentioned before.

**Comment by macasas** [comment]
Hi

When I said “test”, I meant test the skill in the simulator or on a device. The botchat account doesn’t allow me to do that, no-one knows why, so I have the vidmac account.

I tried deleting all the profiles but could not work out how to delete the default one. I uninstalled the extension, rebooted and reinstalled it, and the default profile was still there listed. So how do I remove that?

If you tell me how to remove the default profile, I will happily remove everything again, and just install the vidmac profile to see if that works.

Thanks
Dave

**Comment by nikhilym** [comment]
@macasas , sorry for the late response.

> I uninstalled the extension, rebooted and reinstalled it, and the default profile was still there listed. So how do I remove that?

It is retrieved from your `$HOME/.ask/cli_config` file . You can try renaming that file , and check if profile creation works for you. Please let us know if you face issues.

**Comment by nikhilym** [comment]
Hey @macasas , hope you got this working. I am closing this ticket as resolved. Please reopen if you still face issues. Thanks.

**Comment by macasas** [comment]
Nope!

**Comment by nikhilym** [comment]
Sorry to hear that @macasas . Did you try to backup the `$HOME/.ask/cli_config` file, delete it and recreate the profile through extension, to see if extension works for you?

**Comment by macasas** [comment]
Hi, yes, sorry about that, too many things going on. When I renamed the cli_config file it did the same thing, but when you sent the closed email earlier it reminded me I was going to try again, and this time I deleted the entire .ask folder, and now after importing the skill I get the options to deploy.

Thank you very much for your help in solving this issue, despite my delayed response it is appreciated.

Please go ahead and close this.

**Comment by nikhilym** [comment]
Awesome. Glad to hear you got this working. Closing the issue now. Please let us know your feedback through the multiple options in the extension or any other feature requests. Have a great one!!

**Comment by EugeniuszMartinez** [comment]
Sign in failed.
ASK Alexa with VS Code. Cannot obtain access token. TypeError: Cannot read properties of undefined (reading 'protocol'). What to do with this?

**Comment by tydonelson** [comment]
Hey @EugeniuszMartinez , what's the context you're seeing the error in? Have you created a profile, and during the creation process are you being directed to the Alexa Developer sign-in page in your browser to grant VSCode access?
