### ISSUE TITLE
Import Skill - Credentials for Git-CodeCommit Repository

### ISSUE THREAD

**Issue by barneyparker** [alexa/ask-toolkit-for-vscode#39]
OS: Linux x64 5.7.11-200.fc32.x86_64
Visual Studio Code Version:  1.47.3
Alexa Skills Toolkit Version: 2.0.2
Git Version: git version 2.26.2

**Question**

When trying to import an Alexa skill created in the Alexa Developer console, I am prompted for Git credentials, but I do not know what they should be.  I have tried the AWS account credentials I used when creating the skill, but these are not accepted.

**Steps:**

Under Skill management I click "Download and edit skill"

a dropdown appears with the skill listed, which I click.

I am prompted for a folder to download to, so I select an empty folder

I am then prompted for a Username:

`Git: https://git-codecommit.us-east-1.amazonaws.com (Press 'Enter' to confirm or `Escape` to cancel)`

I am then prompted the same, but for a password.

I have tried:
- the email i use to log in to the developer console
- blank
- escape

Escape cancels, email and blank just display a toast saying:

Skill clone failed. Reason: Git folder setup failed for <dir path>. Reason: Failed to execute git {
  "exitCode": 128,
  "gitErrorCode": "AuthenticationFailed",
  "gitCommand": "fetch",
  "stdout": "",
  "stderr": "fatal: Authentication failed for 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/9f7748b5-b219-440a-89c9-d0ac959a72ab/'\n"
} 

It is not clear what credentials are expected, and i dont believe I have any other credentials I could use.

I have added this as a question as there is a good chance I have missed something.

Thanks for any suggestions :)

**Comment by Chih-Ying** [comment]
Hi @barneyparker,
Thank you for your report. 
I found you are using Git 2.26.x. Based on our investigation, there are some known issues in git 2.25.x and 2.26.x version. These two versions also cannot work correctly to fetch the git credentials in the Alexa Skills Toolkit.
Thus, we will suggest you update to Git >= 2.27. 

Please let us know if the problem persists.

**Comment by nikhilym** [comment]
Thanks for the update @Chih-Ying . To add on that, the `git` credentials that were being asked in the extension, is for the AWS CodeCommit repository that the hosted skill resides at. This is one of the AWS resources `Alexa-hosted skills` service provides when creating a skill, as explained a bit [here](https://developer.amazon.com/en-US/docs/alexa/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#overview). Since this resource is under the service account, your personal AWS login credentials doesn't work here.

To get your hosted skills' `git` credentials, you can call this [SMAPI API](https://developer.amazon.com/en-US/docs/alexa/smapi/alexa-hosted-skill.html#generate-credentials) manually, or use this [ASK CLI](https://developer.amazon.com/en-US/docs/alexa/smapi/ask-cli-command-reference.html#git-credentials-helper) command. However, the `git` credentials provided through this API would be short-lived, and needs to be refreshed periodically, to keep your locally cloned hosted skill git access intact. 

The `ASK Toolkit` extension removes this pain by automatically configuring the credential helper for the hosted skills that are created or downloaded using the extension. It is in this process, that we observed that some specific versions of `git` cannot configure the credential helper properly, leading to this bug. Hopefully if you update the `git` version, you will never be asked for these credentials again :-). 

@barneyparker , hope this explains a bit about the credentials and the issue faced.

**Comment by nikhilym** [comment]
Hey @barneyparker , just checking back if you got around this issue. Please let us know if you are still facing problems.

**Comment by barneyparker** [comment]
Hi @nikhilym apologies for the long delay.  I've just tried to update Git on my local machine, but it appears that 2.26.2 is the latest version available in Fedora32, so updating isn't going to be easy unfortunately.

I'll see if i can find a consistent way to get a newer version installed (i.e. via an official repo rather than a manual install for example) and I'll let you know how it goes

Thanks for your help though, its good to know it was a known issue rather than something I was getting wrong!  You help is very much appreciated :+1:

**Comment by nikhilym** [comment]
Closing this issue since we added an FAQ section about this.
