### ISSUE TITLE
Skill Simulation always returns undefined

### ISSUE THREAD

**Issue by DronNick** [alexa/ask-toolkit-for-vscode#52]
**Desktop (please complete the following information):**

OS: Windows_NT x64 10.0.18362
Visual Studio Code Version:  1.51.0
Alexa Skills Toolkit Version: 2.1.0
Git Version: git version 2.17.1.windows.2

**Question**

While trining to invoke the skill in the simulator I get the following error:
[error - 2020-11-07 22:34:15.671Z] Simulation in progress.

The simulator returns "undefined"

**Comment by nikhilym** [comment]
Hey @DronNick , thanks for raising the issue. To investigate this better, can you provide the skill id and the exact reproduction steps you tried? Also, are you trying to use the simulator on the same profile that you created/cloned the skill?

**Comment by DronNick** [comment]
Hello @nikhilym , I use simulator on the same profile.

`ask-resouces.json`:
```json
{
  "askToolkitResourcesVersion": "2020-04-15",
  "profiles": {
    "default": {
      "skillId": "amzn1.ask.skill.a7c7d3a8-1a49-48bc-a0ea-bd7395c476d8",
      "skillInfrastructure": {
        "type": "@ask-cli/hosted-skill-deployer"
      }
    }
  }
}
```

**Steps to reproduce**
Commit to:
https:// git-codecommit.us-east-1.amazonaws.com/v1/repos/a7c7d3a8-1a49-48bc-a0ea-bd7395c476d8

Deploy skill:
`[info - 2020-11-09 22:07:11.005Z] Skill build succeeded `

Test skill=>Open simulator=> Type invocation and intent (the same string worked before):
```
[error - 2020-11-09 22:09:13.546Z] Simulation in progress. 

[error - 2020-11-09 22:09:14.294Z] Simulation in progress. 

[error - 2020-11-09 22:09:15.657Z] Simulation in progress. 
```
_Talk to Alexa_ screen shows `undefined` as answer

It seems to be a timeout issue - after a while it stops to work and output of the "ASK Toolkit" shows only `Simulation in progress`.

How can i see Lambda function logs?

**Comment by nikhilym** [comment]
Hey @DronNick , you are right. It looks like the invocation failed from the service side and the toolkit is timing out expecting a response. I will check with the service team regarding this skill invocation. To make sure this is a service side issue instead of the toolkit, can you check through developer console or through `ask cli` if the skill invocation is working for this skill and the skill code please?

**Comment by nikhilym** [comment]
Hey @DronNick , just checking back if you were able to get this working. Please let us know. Thanks.

**Comment by DronNick** [comment]
Hello @nikhilym ,

i figured out - it was an issue with the lambda function, it was not starting at all because of the missing modules (deploying failed silently because of yarn module problem). It was only visible in the CloudWatch Logs. I expected that Alexa Skills Toolkit shows this log in the VS Code console. Otherwise what is the purpose of the simulator, if i can not see any error messages localy?

**Comment by nikhilym** [comment]
@DronNick thanks for the update and sorry for the inconvenience. Glad you got it working.

> I expected that Alexa Skills Toolkit shows this log in the VS Code console. Otherwise what is the purpose of the simulator, if i can not see any error messages localy?

You are right, the local simulator should try and retrieve the exact error messages as we do in the web simulator. However, since we use the [skill simulation API](https://developer.amazon.com/en-US/docs/alexa/smapi/skill-simulation-api.html) to get the skill simulation details, it looks like the service is not sending us the correct information regarding these errors. We will check with the team about this. 

Alternatively, we will also check with the hosted skills team if we can get the links for the cloud watch logs for hosted skills, so that we can include it in the skill actions pane.

I logged the feature request #61 . Please add any missing information or any other context to that issue. Thanks.

**Comment by DrMemoryFish** [comment]
im also getting this error, i may need some help.
