### ISSUE TITLE
Welcome page is not showing

### ISSUE THREAD

**Issue by balsimpson** [alexa/ask-toolkit-for-vscode#58]
am using VS Code extension and absolutely nothing happens when I click on the Alexa icon on the sidebar. am on a Mac running Catalina. I tried uninstalling and reloading but no change. I had an earlier version that i was using and it worked without any problems. once I upgraded to 2.1 is when it's giving me problems.
![image](https://user-images.githubusercontent.com/16057289/98929410-1a37ed80-2501-11eb-891e-12c7ea0cfe0d.png)

**Comment by nikhilym** [comment]
@balsimpson , thanks for raising the bug. To investigate this a bit better, can you please do the following : 

- Navigate to the vscode settings -> Extensions -> Alexa Skills Kit
- Change the `Ask Toolkit: Log Level` value to `verbose`
- Save and close the settings file
- Open the `Output` tab (from `View` menu)
- Click on the toolkit extension icon
- Change the Output dropdown to `Ask Toolkit` and provide that debug info

Additionally, can you try installing the older version of the extension, to check if that is working as expected for you?

**Comment by balsimpson** [comment]
Thank you for the reply. The error showed that `.ask/cli_config` was invalid JSON. I removed the folder and the extension shows up correctly.

**Comment by nikhilym** [comment]
Thanks @balsimpson . Glad that you got it working. 

Adding this note for any other user, who might stumble upon this bug later. Since `ASK Toolkit` and `ASK CLI` uses the same profile configuration from `.ask/cli_config`, you could have just removed that folder and used the extension directly. We have the [`sign in` flow](https://github.com/alexa/ask-toolkit-for-vscode#sign-in-to-your-amazon-developer-account) integrated in the extension, that will help you configure it similar to the CLI. 

Hope you are finding the extension useful. Please let us know if you have any additional issues/feature requests or questions about the extension. A review would be fine too :-) . I am going ahead and closing this bug @balsimpson . Thanks.
