### ISSUE TITLE
Possibly invalid skill.json warning

### ISSUE THREAD

**Issue by steveoh** [alexa/ask-toolkit-for-vscode#6]
**Description:**

**skill.json** `manifest.apis.custom.endpoint` validation might be incorrect. When pointing a skill at a lambda function, the entry is of the form: 

```json
"uri": "lambda-function-name",
"sourceDir": "lambda/py"
```

The linter shows this error `String does not match the pattern of "^(arn|https://)".`:

```json
  "owner": "_generated_diagnostic_collection_name_#0",
  "severity": 4,
  "message": "String is not a URI: URI with a scheme is expected."
```

The arn does not seem to be required. The arn address is generated, stored, and managed in the `.ask/config` after a deployment. 

The linter also shows the property `sourceDir` is not allowed. I am confused because all of the [ask-skill samples](https://github.com/alexa/skill-sample-python-helloworld-decorators/blob/master/skill.json#L21-L28) use that form.

```json
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 4,
	"message": "Property sourceDir is not allowed.",
```

I have noticed that the [skill manifest](https://developer.amazon.com/docs/smapi/skill-manifest.html#custom) doesn't make mention of these values. Are they ask-cli specific?

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**

osx 10.14.3 

**VS Code version**:

Version 1.31.1

**Comment by steveoh** [comment]
bump

**Comment by ShenChen-Amazon** [comment]
Hi @steveoh ,
Sorry for responding so late and thanks for reporting this issue. We do find this problem exist, and we will have a look into it and try to solve it as soon as possible. 

Best,
Shen

**Comment by ShenChen-Amazon** [comment]
@steveoh The JSON validation has been updated and this problem has been fixed. Please check. If this problem still exists, you can try to reload the plugin or restart vscode. Thx.

**Comment by steveoh** [comment]
looks good thanks!

**Comment by dilunika** [comment]
Still, this issue is there when you build from AWS CodePipeline Alexa Skill Deploy provider.
`Object instance at property path "$.manifest.apis.custom.endpoint" has unexpected property: "sourceDir".`
![Screen Shot 2020-01-09 at 11 00 46 AM](https://user-images.githubusercontent.com/3152971/72019945-89382a80-32cf-11ea-85c0-dd9b7af2d977.png)

**Comment by RonWang** [comment]
Hey @dilunika , when you use AWS CodePipeline to deploy Alexa Skill, you might need to avoid deploying your skill.json with "sourceDir" field inside. 

This field is an ask-cli v1.x `ask deploy` specific field (not quite related to VSCode's file linter) and thus failure happens when it's deployed using AWS CodePipeline. I'd suggest you follow https://docs.aws.amazon.com/codepipeline/latest/userguide/tutorials-alexa-skills-kit.html#tutorials-alexa-skills-kit-push 's steps to deploy through CodePipeline, especially use `ask api get-skill -s skill-ID > skill.json` to get a CodePipeline supported skill.json file.

**Comment by jkdilunika** [comment]
Thanks @RonWang .
