### ISSUE TITLE
Add ability to just deploy code.

### ISSUE THREAD

**Issue by s-maheshbabu** [alexa/ask-toolkit-for-vscode#69]
**Is your feature request related to a problem? Please describe.**

Today, the ASK extension lets us deploy and build the code. Building code is a time consuming process and slows down the development turn around time when trying to test changes on physical devices. 

Moreover, [Alexa Conversations](https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2020/07/introducing-alexa-conversations-beta-a-new-ai-driven-approach-to-providing-conversational-experiences-that-feel-more-natural) skills literally take 30 to 60 minutes to build. 

So, there should be a way to just deploy the code to lambda.

**Describe alternatives you've considered**

Not using Alexa hosted skills and maintaining my own lambda will enable the desired development flow.

**Comment by nikhilym** [comment]
Hey @s-maheshbabu , thanks for the feature request. Today, we only support Alexa-hosted skills in the extension. That means, a deployment would mean deploying the whole skill folder containing skill package and code. The Alexa-hosted skill service will decouple these and deploy the resources in the backend intelligently => if there is no change in code or no change in skill package, that particular resource deployment is not triggered. Hence, the development turn around time is not affected. 

Just to understand your feature request little better, can you please let us know the following : 

- In this feature request, are you suggesting the toolkit to provide support for deploying individual skill resources in Alexa-hosted skills? You can achieve this by `git commit` and `git push` only needed resources for deployment right? Do you think we need to improve on this?

- If the request is for deploying code to lambda for non Alexa-hosted skills, then

  - We currently do not support creation/cloning of non Alexa-hosted skills from the toolkit. Do you want us to prioritize on supporting such skills? 
  - Configuring skill code deployments are a bit tricky, since there are multiple endpoints that the code can be deployed to. Moreover, skill developers can host their code in AWS Lambda or can use other hosting platforms. It would not be feasible to support all such deployment options. Instead we can maybe look at providing hooks for skill deployment, that skill devs can configure for their code deployments. Do you think such an option would be feasible?

**Comment by nikhilym** [comment]
@s-maheshbabu , do you have any thoughts on the questions we had?

**Comment by s-maheshbabu** [comment]
Sorry that my original report wasn't clear. Let me describe the scenario. 

* I have an Alexa-Conversations (AXC) skill that is configured as an Alexa-hosted skill.
* Some AXC skill artifacts (ex, APL responses) can be modified from VSCode but it is not 'yet' possible to modify other skill artifacts (like utterance sets, dialog acts etc.) from VS Code. So, I go to the developer console for all changes. 
* I use VS Code to make regular code changes.

Now, when I try to deploy, two things happen - 
1. VS Code will overwrite the skill artifacts changes I made using the developer console because it sees differences. There is no way to prevent that.
2. VS Code deployment will take about 30 to 60 minutes because it tries to build the skill. There is no way to bypass skill deployment. 

I understand this is particularly a problem for Alexa-Conversations skills which don't yet fully support editing a skill through VS Code. However, this is a common problem whenever Alexa releases major new features. They usually only support dev console at launch and VSCode/ask-cli support comes later. 

So, my request is to just give developers an option to only deploy to lambda and not build the skill. That way I can make skill-package changes in dev console and use VSCode for the rest of development.

**Comment by nikhilym** [comment]
Hey @s-maheshbabu , sorry for responding late. I was trying this out with a `Alexa-Conversations` skill to help you better. So this is what I tried, built an AXC skill from dev console, cloned it through the toolkit and changed different skill artifacts, to see what is the effect : 

- On first clone, since local skill setup needs the toolkit to export skill-package and set it up as a formal structure under your hosted skill CodeCommit repo, the initial commit on clone will lead to a skill model & skill code deployment. This is at the moment unavoidable, because of the way Alexa-hosted skills sets up the initial AWS CodeCommit repo. We will check with the corresponding team if they can take this as a feature request.

- When there is a change in skill-code, then on deployment, only skill-code is updated and deployed. Skill model artifacts are not updated and hence a subsequent model deployment is not triggered.

- When there are APL response changes in developer console but they are only `saved` and models are not `built`, they will be overwritten by the skill-package from your local changes. This is a known behavior with APL and skill-package, and the corresponding team is looking to improve the experience. FYI, this current behavior exists for non Alexa-Conversations skills as well. We sent the feedback to the corresponding service team and waiting for an update on the fix. Sorry for the inconvenience.

----

> I understand this is particularly a problem for Alexa-Conversations skills which don't yet fully support editing a skill through VS Code. However, this is a common problem whenever Alexa releases major new features. They usually only support dev console at launch and VSCode/ask-cli support comes later.

We understand this a problem and a major pain point for the skill developers using our tools. I will discuss this with the team, to figure out a better way of supporting new features on day-1 of their releases on developer console. 

> So, my request is to just give developers an option to only deploy to lambda and not build the skill. That way I can make skill-package changes in dev console and use VSCode for the rest of development.

Thanks for the context, and this makes more sense now. You should be able to do this today, by only checking in files under `lambda` folder of your skill and doing the deployments through the toolkit. Did you try that out and see if it works as expected for you?

**Comment by s-maheshbabu** [comment]
You acknowledged two issues and that is good. 
Yes, carefully checking in the files only under lambda/ works as expected but it is just a bad experience because I need to remember to not make any changes outside the folder. 

As I see, the teams are aware of these issues and working on fixes. So, we are good here.

**Comment by nikhilym** [comment]
Thanks @s-maheshbabu . Thanks for providing valuable feedback. I have forwarded your feedback to the concerned teams. Since this doesn't relate directly to the toolkit itself, I am going ahead and closing this issue.
