### ISSUE TITLE
Any known problems with vscode Intellisense and this extension

### ISSUE THREAD

**Issue by mrosin** [alexa/ask-toolkit-for-vscode#79]
**Desktop (please complete the following information):**

-   OS: OS X 10.14.6
-   VS Code version: 1.52.1
-   Alexa Skill Toolkit extension version: 2.2.0

**Question**
Hi, 

Have you received or experienced problems with Intellisense coupled with this extension. 

When creating a fresh example skill with no modifications there seems to be some problems with Intellisense. Does not correct typos or find dependencies to suggest or correct. Minor thing but quite annoying? Have been trying to find out why this happens, together with friend, but no luck and we are stunned. 

Screenshots showing how IntelliJIDEA has no problems finding dependencies whilst vscode interprets it in no way.

All other javascript/node projects show no issue, therefor thinking it might have something todo with this extension or how it creates the project? 

<img width="635" alt="Screenshot 2021-01-04 at 21 56 36" src="https://user-images.githubusercontent.com/4101925/103574289-50c62f00-4ed8-11eb-8dc1-9277c3ce8477.png">
<img width="908" alt="Screenshot 2021-01-04 at 21 55 44" src="https://user-images.githubusercontent.com/4101925/103574295-53288900-4ed8-11eb-83f4-10b5d2385eff.png">

**Comment by nikhilym** [comment]
Hey @mrosin , sorry for responding late. I could reproduce this issue but tested that this is not related to the extension. I deleted the extension completely from vscode but still get the same issue. Also, when I annotate the `LaunchRequestHandler` to be a `RequestHandler` type (you can see that it is an error on JS side, but if the file is a TS file, it works as expected), then VSCode is able to provide the intellisense

![Screen Shot 2021-01-05 at 5 16 37 PM](https://user-images.githubusercontent.com/25237515/103717262-dfd75380-4f79-11eb-81e0-aeebe09aa2e9.png)

This intellisense configuration seems to be coming from vscode itself. I will check in vscode docs if there is any specific configuration that needs to be done on the project and update here. But otherwise, this seems to be unrelated to the extension.
