### ISSUE TITLE
Deploying Skill hangs.

### ISSUE THREAD

**Issue by solarslurpi** [alexa/ask-toolkit-for-vscode#83]
**Describe the bug**

Following steps in [VOICE Summit: Alexa Visual Studio Code Plugin](https://youtu.be/nIL1qrZmhSI?t=474).  After pressing the Deploy Button, "Deploying Skill: Skill building in Progress" notification does not go away.  I check the Developer's console and the change to the Invocation words are still "change me"

**To Reproduce**
FOLLOW STEPS IN VOICE VIDEO (Link above)

**Extension Logs**

**Expected behavior**
Skill completes.  Testing works.  This is very simple hello world.

**Desktop (please complete the following information):**

OS: Windows_NT x64 10.0.18363
Visual Studio Code Version:  1.52.1
Alexa Skills Toolkit Version: 2.2.0
Git Version: git version 2.29.2.windows.2

**Comment by nikhilym** [comment]
Hey @solarslurpi , sorry for responding late. I just tried the same with the latest extension and deployment works as expected. The notification takes some time since we use a poller to check if the skill build status, and provide a final status once we get the same from the console.

Can you please share the skill id and rough timestamps on when you tried this? Also can you try it once again and let us know if there are any errors?

**Comment by nikhilym** [comment]
Hey @solarslurpi , did you get a chance to retry this and see if you are still facing the problem?
