### ISSUE TITLE
Custom build directory when using Deploy skill

### ISSUE THREAD

**Issue by matijagrcic** [alexa/ask-toolkit-for-vscode#89]
When using the Alexa Skills Toolkit it seems the following

```json
"code": {
      "default": {
        "src": "./lambda/build"
      }
    }
```

isn't taken into account and only whats on the default location `lambda/index.js` is used when initiating deploy.
Is this by design or can we specify a custom directory?

Use case here is usage of TypeScript where the `build` directory contains the output.

**Comment by Chih-Ying** [comment]
@matijagrcic 

Thank you for your report. 

It seems your skill is a self-hosted skill (non Alexa hosted skill). In the ASK Toolkit v.2.3.0, we start supporting self-hosted skills creation and deployment, but it's only for the skill pacakge. Lambda code can be manually retrieved and deployed, depending on how you source control your code.

In your case, I will suggest you to use ASK-CLI to deploy the skill code (see the [document](https://github.com/alexa/ask-cli/blob/develop/docs/concepts/Deploy-Command.md#code-builder)). 
You have to build your Typescript code (ASK-CLI won't build it automatically), and then specify the entry point for your lambda code in the `ask-resources.file`, it will be something like `lambda/dist/index.js`.

Please let me know if there are any questions.Thanks

**Comment by matijagrcic** [comment]
Hey @Chih-Ying thanks for responding.
The skill is a Alexa hosted skill which i have pulled down using the ASK Toolkit. 

```js
//ask-resources.json
"skillInfrastructure": {
    "type": "@ask-cli/hosted-skill-deployer"
}
```

Given it's a Alexa hosted skill the source control is git so just a push or a ASK Toolkit Deployment work great as long as the `index.js` is changed.

I know I need to build the TypeScript myself, and I've setup all that, but given the index.js needs to change and that's generated by TypeScript I don't want it included in the repo but providing the other location doesn't work, that is the ASK Toolkit doesn't seem to pick up the location it just does the git push.

```js
//ask-resources.json
"code": {
      "default": {
        "src": "./lambda/build"
     }
}
```

Is there any plans to support this thru ASK Toolkit and not jus the ASK-CLI?

**Comment by Chih-Ying** [comment]
Hi @matijagrcic

Thanks for the clarification.

ASK Toolkit handles Alexa hosted skills deployment in a different way. As you mentioned, ASK Toolkit uses git to do source control. In the deployment process, Ask Toolkit executes the `git push` operation to push the whole skill project to Alexa CodeCommit repo, but does not do any files verification. That is the reason why specifying the lambda code source path in `ask-resources.json` does not work for an Alexa hosted skill.

The Alexa service will build the skill code. Since `./lambda/index.js` is the required entry point for Alexa service, I think you can try to move all the Typescript build code under the `lambda` folder, and make sure you have `index.js` as the entry file. 
 
Please let me know if there are any questions.Thanks!

**Comment by matijagrcic** [comment]
Yeah, specifying the `outDir `in `tsconfig.json` to be lambda folder and the include to be `index.ts` is working as expected as pointed before but then the compiled files are now part of the repo, which is what I'm trying to avoid.

Is there a way we can avoid this, maybe with Git hooks `post-receive ` or something?

**Comment by Chih-Ying** [comment]
Hi @matijagrcic 
The Alexa hosted service does not support Typescript for now, so the compiled files (Javascript files) need to be included in the repo.
I have brought this request to the service team and tag this issue as a feature request. Thank you.

**Comment by matijagrcic** [comment]
Thanks @Chih-Ying, appreciate it, would be great if the TS support lands.
